### ISSUE TITLE
The testing results of the whole dataset is empty.

### ISSUE THREAD

**Issue by cici-999** [zhanggang001/RefineMask#29]
First of all, thank you very much for sharing your work. I tested on coco dataset, but the test result showed that the whole dataset was empty. May I ask how to solve this problem? thanks.

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5000/5000, 18.3 task/s, elapsed: 273s, ETA:     0s
writing results to work_dirs/r50-refinemask-1x/result.pkl

Evaluating bbox...
Loading and preparing results...
The testing results of the whole dataset is empty.
load gt json
load pred json
Traceback (most recent call last):
  File "/data/user-njf86/ding/RefineMask-main/tools/test.py", line 153, in <module>
    main()
  File "/data/user-njf86/ding/RefineMask-main/tools/test.py", line 149, in main
    dataset.evaluate(outputs, args.eval, classwise=True, **kwargs)
  File "/data/user-njf86/ding/RefineMask-main/mmdet/datasets/coco.py", line 556, in evaluate
    metric='segm',
  File "/data/user-njf86/ding/RefineMask-main/mmdet/datasets/coco.py", line 655, in eval_cocofied_lvis_result
    lvis_dt = LVISResults(lvis_gt, result_file)
  File "/home/user-njf/anaconda3/envs/mmdet_test/lib/python3.6/site-packages/lvis/results.py", line 44, in __init__
    if 'bbox' in result_anns[0]:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user-njf/anaconda3/envs/mmdet_test/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user-njf/anaconda3/envs/mmdet_test/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user-njf/anaconda3/envs/mmdet_test/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user-njf/anaconda3/envs/mmdet_test/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user-njf/anaconda3/envs/mmdet_test/bin/python', '-u', '/data/user-njf86/ding/RefineMask-main/tools/test.py', '--local_rank=0', './configs/refinemask/coco/r50-refinemask-1x.py', 'work_dirs/r50-refinemask-1x/latest.pth', '--launcher', 'none', '--eval', 'bbox', 'segm', '--out', 'work_dirs/r50-refinemask-1x/result.pkl', '--tmpdir', 'work_dirs/r50-refinemask-1x/tmpdir']' returned non-zero exit status 1.

**Comment by zhanggang001** [comment]
Please make sure that you load the checkpoint correctly.

**Comment by cici-999** [comment]
Very thanks to your prompt reply！
