### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by kevins99** [zhanggang001/RefineMask#5]
Hi! While training on the coco dataset using the specified file I get the following error log: 
train_detector(
  File "/home2/kevins99/RefineMask/mmdet/apis/train.py", line 145, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in train
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home2/kevins99/RefineMask/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home2/kevins99/RefineMask/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home2/kevins99/RefineMask/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home2/kevins99/RefineMask/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/home2/kevins99/RefineMask/mmdet/models/dense_heads/base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home2/kevins99/RefineMask/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home2/kevins99/RefineMask/mmdet/models/dense_heads/anchor_head.py", line 572, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/home2/kevins99/RefineMask/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/ops/nms.py", line 243, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/utils/misc.py", line 262, in new_func
    output = old_func(*args, **kwargs)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/ops/nms.py", line 17, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: no kernel image is available for execution on the device

Following the mmcv documentation, I have built it again with the same CUDA version. 
Link: https://mmcv.readthedocs.io/en/latest/trouble_shooting.html#:~:text=%E2%80%9CRuntimeError%3A%20nms%20is%20not%20compiled,folder%20before%20re%2Dcompile%20mmcv.

My enviorment seems to be correctly setup. The environment details are as follows:

Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.5.2
MMCV: 1.0.5
MMDetection: ('2.3.0',)
MMDetection Compiler: GCC 5.5
MMDetection CUDA Compiler: 10.2

Finally, I have tried PyTorch 1.5.0 along with mmcv-full 1.0.5 which resulted in the following error log: 
Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 67, in <module>
    for name, val in collect_env().items():
  File "mmdet/utils/collect_env.py", line 60, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home2/kevins99/anaconda3/envs/cvit/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home2/kevins99/anaconda3/envs/cvit/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z13__THCudaCheck9cudaErrorPKci

All mmcv modules have been built with the correct PyTorch and cuda versions using the command
pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

Help would be greatly appreciated. 
Many thanks in advance!

**Comment by zhanggang001** [comment]
I'm sorry to reply to your question so late. If you  have not solved this problem, you can try `pip install mmcv-full==1.0.5 -f https://download.openmmlab.com/mmcv/dist/\cu90/\torch1.5.0/index.html`.
